"""empty message

Revision ID: 74b8855a8c6c
Revises: 
Create Date: 2017-04-23 11:47:23.843336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74b8855a8c6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    op.drop_table('Person')
    op.drop_table('picture_values')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture_values',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('picture1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('picture2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'picture_values_pkey')
    )
    op.create_table('Person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Person_pkey')
    )
    op.create_table('pictures',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'pictures_pkey')
    )
    # ### end Alembic commands ###
